/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Events
self.addEventListener('push', (event) => {
  if (event.data) {
    try {
      const data = event.data.json();
      const options: any = {
        body: data.body,
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        data: {
          url: data.url || '/'
        },
        actions: [
          {
            action: 'open',
            title: 'Xem ngay'
          },
          {
            action: 'close',
            title: 'Đóng'
          }
        ],
        vibrate: [100, 50, 100],
        tag: 'strategic-update',
        renotify: true
      };

      event.waitUntil(
        self.registration.showNotification(data.title || 'Cảnh báo Hệ thống Elite', options)
      );
    } catch (e) {
      // Fallback for simple message
      const text = event.data.text();
      event.waitUntil(
        self.registration.showNotification('Cảnh báo Hệ thống Elite', {
          body: text,
          icon: '/pwa-192x192.png'
        })
      );
    }
  }
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'close') return;

  const urlToOpen = event.notification.data.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window client is already open, focus it
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return (client as WindowClient).focus();
        }
      }
      // Otherwise, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
